# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.10-alpine
WORKDIR /app

# Install dependencies
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY . ./

# Expose port if needed, though MCP uses stdio

# Command to run the MCP server. Provide the Facebook token via the FB_ACCESS_TOKEN
# environment variable (e.g. `docker run -e FB_ACCESS_TOKEN=... <image>`) so it does
# not appear in the container's command line.
ENV FB_ACCESS_TOKEN=""
CMD ["python", "server.py"]
